package com.aakash.ai.springragopenai;


import jakarta.annotation.PostConstruct;
import org.jspecify.annotations.NonNull;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.reader.pdf.PagePdfDocumentReader;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.SimpleVectorStore;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.core.io.UrlResource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;

@RestController
public class RAGController {

    private final ChatClient chatClient;
    private final VectorStore vectorStore;
    private final ChatMemory chatMemory;

    public RAGController(ChatClient.Builder chatBuilder, EmbeddingModel embeddingModel, ChatMemory chatMemory)
    {
        this.chatClient = chatBuilder.build();
        this.vectorStore = SimpleVectorStore.builder(embeddingModel)
                .build();
        this.chatMemory = chatMemory;
    }

    @PostConstruct
    public void initConstruct() throws Exception
    {
        var pdfUrl = "https://certificationexams.pro/docs/pickeringisspringfield.pdf";
        var resource = new UrlResource(new URI(pdfUrl));
        // Load The PDF.
        var pages = new PagePdfDocumentReader(resource).get();
        // Add to Vector Store.
        vectorStore.add(pages);
    }


    /**
     * API is called with a question and a conversation ID (cid).
     * The question is added to the chat memory, and an augmented prompt is generated by retrieving relevant pages from the vector store.
     * The augmented prompt is then sent to the chat client, which generates a response based on the retrieved context.
     * The generated response is added to the chat memory and returned as the API response.
     *
     * @param cid - Conversation Unique ID
     * @param question -  Question to be asked
     * @return response from PDF fie.
     */
    @GetMapping("/ask")
    public String ask(@RequestParam String cid, @RequestParam String question)
    {
        chatMemory.add(cid, new UserMessage(question));

        var prompt = generateAugmentedPrompt(question);

        var history = chatMemory.get(cid);

        var generatedContext = chatClient.prompt(prompt).messages(history).call().content();
        System.out.println("Generated Context: " + generatedContext);

        chatMemory.add(cid, new AssistantMessage(generatedContext));

        return generatedContext;
    }

    /**
     * Generates an augmented prompt by retrieving relevant pages from the vector store based on the question.
     *
     * @param question - String
     * @return Augmented Prompt
     */
    private @NonNull String generateAugmentedPrompt(final String question) {
        var retrieveQuery = SearchRequest.builder().query(question).topK(5).build();
        var retrievedPages = vectorStore.similaritySearch(retrieveQuery);
        var augmentedContext = new StringBuilder();
        for(int i = 0; i < retrievedPages.size(); i++)
        {
            augmentedContext.append("Page ").append(i+1).append(": ").append(retrievedPages.get(i).getText()).append("\n");
        }

        var prompt = """
                You are answering questions using only the context provided form the popular Pickering is Springfield book.
                If the answer is not in the context, say "I don't know, given the pages of the book I've read.
                Maybe ask me a different question?"
                
                CONTEXT:
                %s
                
                QUESTION:
                %s
                """.formatted(augmentedContext, question);

        System.out.println(prompt);
        return prompt;
    }

}
