package com.aakash.ai.springragopenai.controller;

import com.aakash.ai.springragopenai.service.RAGService;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class RAGController {

    private final ChatClient chatClient;
    private final ChatMemory chatMemory;
    private final RAGService ragService;

    public RAGController(ChatClient.Builder chatBuilder, ChatMemory chatMemory, RAGService ragService)
    {
        this.chatClient = chatBuilder.build();
        this.chatMemory = chatMemory;
        this.ragService = ragService;
    }

    /**
     * API is called with a question and a conversation ID (cid).
     * The question is added to the chat memory, and an augmented prompt is generated by retrieving relevant pages from the vector store.
     * The augmented prompt is then sent to the chat client, which generates a response based on the retrieved context.
     * The generated response is added to the chat memory and returned as the API response.
     *
     * @param cid - Conversation Unique ID
     * @param question -  Question to be asked
     * @return response from PDF file.
     */
    @GetMapping("/ask")
    public String ask(@RequestParam String cid, @RequestParam String question)
    {
        chatMemory.add(cid, new UserMessage(question));

        var prompt = this.ragService.generateAugmentedPrompt(question);

        var history = chatMemory.get(cid);

        var generatedContext = chatClient.prompt(prompt).messages(history).call().content();
        System.out.println("Generated Context: " + generatedContext);

        chatMemory.add(cid, new AssistantMessage(generatedContext));

        return generatedContext;
    }
}
